#!/bin/sh
# A script to start ProtonVPN via OpenVPN on Slackware
# Assumes full installation of Slackware-current

# Can change VPN_CONFIG if you want to use a different VPN
VPN_CONFIG="/etc/openvpn/proton/ca-free-4.protonvpn.udp.ovpn"

# Re-invoke ourselves as root via su if not already root
# That is, if UID doesn't equal 0 (which is Root's), then
# re-run vpn_start program with sudo privileges.
if [ "$(id -u)" -ne 0 ]; then
    exec su -c "$0"
fi

# Disable IPv6
# Not really a good solution
# Honestly, writing this script was a lot harder than
# just using the ProtonVPN slackbuild script :(
echo "Disabling IPv6..."
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1

# This function will restart IPv6 when run
cleanup() {
    echo "Re-enabling IPv6..."
    sysctl -w net.ipv6.conf.all.disable_ipv6=0
    sysctl -w net.ipv6.conf.default.disable_ipv6=0
}

# When the program exits, run the cleanup function
# to re-enable IPv6
trap cleanup EXIT

# The actual OpenVPN program
echo "Starting ProtonVPN..."
openvpn --config "$VPN_CONFIG"
